// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDERs8C8DCJTZt0T5Yw5VHMHB0koZ5wxx0',
    appId: '1:378070928151:web:82c7c855b393c3dd4a0552',
    messagingSenderId: '378070928151',
    projectId: 'flutter-academia-c84d2',
    authDomain: 'flutter-academia-c84d2.firebaseapp.com',
    storageBucket: 'flutter-academia-c84d2.firebasestorage.app',
    measurementId: 'G-B6SN979JZ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaiMyLG9HseIGWzJRjmg49wr2fiW7x49k',
    appId: '1:378070928151:android:eee431b35bc23fb44a0552',
    messagingSenderId: '378070928151',
    projectId: 'flutter-academia-c84d2',
    storageBucket: 'flutter-academia-c84d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB01HK2H4sK8pB9UpRuth4M1gGnMZSLTWI',
    appId: '1:378070928151:ios:a83bbf7831913ec44a0552',
    messagingSenderId: '378070928151',
    projectId: 'flutter-academia-c84d2',
    storageBucket: 'flutter-academia-c84d2.firebasestorage.app',
    iosBundleId: 'com.example.flutterAcademia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDERs8C8DCJTZt0T5Yw5VHMHB0koZ5wxx0',
    appId: '1:378070928151:web:a1df763723ef29474a0552',
    messagingSenderId: '378070928151',
    projectId: 'flutter-academia-c84d2',
    authDomain: 'flutter-academia-c84d2.firebaseapp.com',
    storageBucket: 'flutter-academia-c84d2.firebasestorage.app',
    measurementId: 'G-K38PKVPSD9',
  );
}