import '../../dominio/entidades/exercicios.dart';

final List<Exercicio> exercicios = [
  // ----- ACADEMIA - INICIANTE -----
  Exercicio(
    nome: "Supino Reto Barra",
    imagem: "assets/images/supino-reto-barra.png",
    tipoEquipamento: "academia",
    linkYoutube: "pCPyqW60Wuk",
    tags: ["iniciante", "treinoA"],
  ),
  Exercicio(
    nome: "Supino Inclinado Halter",
    imagem: "assets/images/supino_inclinado.png",
    tipoEquipamento: "academia",
    linkYoutube: "F4Q1g2z8MWM",
    tags: ["iniciante", "treinoA"],
  ),
  Exercicio(
    nome: "Flexão de Braço",
    imagem: "assets/images/flexao.png",
    tipoEquipamento: "peso_corporal",
    linkYoutube: "dHgoYiCraCw",
    tags: ["iniciante", "treinoA"],
  ),
  Exercicio(
    nome: "Tríceps Corda Polia",
    imagem: "assets/images/triceps_corda.png",
    tipoEquipamento: "academia",
    linkYoutube: "dTqDKC0D6P4",
    tags: ["iniciante", "treinoA"],
  ),

  Exercicio(
    nome: "Barra Fixa Assistida",
    imagem: "assets/images/barra_fixa.png",
    tipoEquipamento: "academia",
    linkYoutube: "thg6cGXSlvY",
    tags: ["iniciante", "treinoB"],
  ),
  Exercicio(
    nome: "Remada Unilateral Halter",
    imagem: "assets/images/remada-unilateral-halter.png",
    tipoEquipamento: "academia",
    linkYoutube: "m4h4jT9patY",
    tags: ["iniciante", "treinoB"],
  ),
  Exercicio(
    nome: "Pulldown Polia Alta",
    imagem: "assets/images/pulldown-polia-alta.png",
    tipoEquipamento: "academia",
    linkYoutube: "v6-QIOY0nW0",
    tags: ["iniciante", "treinoB"],
  ),
  Exercicio(
    nome: "Rosca Direta Barra",
    imagem: "assets/images/rosca_direta.png",
    tipoEquipamento: "academia",
    linkYoutube: "s4B8UW3BMqk",
    tags: ["iniciante", "treinoB"],
  ),

  Exercicio(
    nome: "Agachamento Livre Barra",
    imagem: "assets/images/agachamento-livre.png",
    tipoEquipamento: "academia",
    linkYoutube: "IGf9fR4Y7Iw",
    tags: ["iniciante", "treinoC"],
  ),
  Exercicio(
    nome: "Leg Press",
    imagem: "assets/images/legpress.png",
    tipoEquipamento: "academia",
    linkYoutube: "nY8UsiAqwds",
    tags: ["iniciante", "treinoC"],
  ),
  Exercicio(
    nome: "Cadeira Extensora",
    imagem: "assets/images/cadeira-extensora.png",
    tipoEquipamento: "academia",
    linkYoutube: "el3oHblB5DM",
    tags: ["iniciante", "treinoC"],
  ),
  Exercicio(
    nome: "Desenvolvimento Militar Halter",
    imagem: "assets/images/desenvolvimento-com-halteres.png",
    tipoEquipamento: "academia",
    linkYoutube: "L-iQfHVeuVg",
    tags: ["iniciante", "treinoC"],
  ),

  // ----- ACADEMIA - INTERMEDIÁRIO -----
  Exercicio(
    nome: "Supino Reto Barra",
    imagem: "assets/images/supino-reto-barra.png",
    tipoEquipamento: "academia",
    linkYoutube: "pCPyqW60Wuk",
    tags: ["intermediario", "treinoA"],
  ),
  Exercicio(
    nome: "Supino Inclinado Halter",
    imagem: "assets/images/supino_inclinado.png",
    tipoEquipamento: "academia",
    linkYoutube: "F4Q1g2z8MWM",
    tags: ["intermediario", "treinoA"],
  ),
  Exercicio(
    nome: "Crucifixo Inclinado Halter",
    imagem: "assets/images/crucifixo-inclinado-halteres.png",
    tipoEquipamento: "academia",
    linkYoutube: "uy9Xk3SVrms",
    tags: ["intermediario", "treinoA"],
  ),
  Exercicio(
    nome: "Crossover Polia Alta",
    imagem: "assets/images/crossover-polia-alta.png",
    tipoEquipamento: "academia",
    linkYoutube: "E3aha5zhlc0",
    tags: ["intermediario", "treinoA"],
  ),
  Exercicio(
    nome: "Tríceps Corda Polia",
    imagem: "assets/images/triceps_corda.png",
    tipoEquipamento: "academia",
    linkYoutube: "dTqDKC0D6P4",
    tags: ["intermediario", "treinoA"],
  ),

  Exercicio(
    nome: "Barra Fixa",
    imagem: "assets/images/barra-fixa.png",
    tipoEquipamento: "academia",
    linkYoutube: "thg6cGXSlvY",
    tags: ["intermediario", "treinoB"],
  ),
  Exercicio(
    nome: "Remada Curvada Barra",
    imagem: "assets/images/remada-curvada-barra.png",
    tipoEquipamento: "academia",
    linkYoutube: "TfxJMertfsw",
    tags: ["intermediario", "treinoB"],
  ),
  Exercicio(
    nome: "Remada Unilateral Halter",
    imagem: "assets/images/remada-unilateral-halter.png",
    tipoEquipamento: "academia",
    linkYoutube: "m4h4jT9patY",
    tags: ["intermediario", "treinoB"],
  ),
  Exercicio(
    nome: "Pulldown Polia Alta",
    imagem: "assets/images/pulldown-polia-alta.png",
    tipoEquipamento: "academia",
    linkYoutube: "v6-QIOY0nW0",
    tags: ["intermediario", "treinoB"],
  ),
  Exercicio(
    nome: "Rosca Alternada Halter",
    imagem: "assets/images/rosca_alternada.png",
    tipoEquipamento: "academia",
    linkYoutube: "S1HAcTVQVYE",
    tags: ["intermediario", "treinoB"],
  ),

  Exercicio(
    nome: "Agachamento Livre Barra",
    imagem: "assets/images/agachamento-livre.png",
    tipoEquipamento: "academia",
    linkYoutube: "IGf9fR4Y7Iw",
    tags: ["intermediario", "treinoC"],
  ),
  Exercicio(
    nome: "Leg Press",
    imagem: "assets/images/legpress.png",
    tipoEquipamento: "academia",
    linkYoutube: "nY8UsiAqwds",
    tags: ["intermediario", "treinoC"],
  ),
  Exercicio(
    nome: "Cadeira Extensora",
    imagem: "assets/images/cadeira-extensora.png",
    tipoEquipamento: "academia",
    linkYoutube: "el3oHblB5DM",
    tags: ["intermediario", "treinoC"],
  ),
  Exercicio(
    nome: "Cadeira Flexora",
    imagem: "assets/images/cadeira-flexora.png",
    tipoEquipamento: "academia",
    linkYoutube: "Zss6E3VU6X0",
    tags: ["intermediario", "treinoC"],
  ),
  Exercicio(
    nome: "Panturrilha em Pé",
    imagem: "assets/images/panturrilha.png",
    tipoEquipamento: "academia",
    linkYoutube: "95MEoNZKaP0",
    tags: ["intermediario", "treinoC"],
  ),

  Exercicio(
    nome: "Desenvolvimento Militar Barra",
    imagem: "assets/images/desenvolvimento-com-halteres.png",
    tipoEquipamento: "academia",
    linkYoutube: "L-iQfHVeuVg",
    tags: ["intermediario", "treinoD"],
  ),
  Exercicio(
    nome: "Elevação Lateral Halter",
    imagem: "assets/images/elevacao-lateral.png",
    tipoEquipamento: "academia",
    linkYoutube: "IwWvZ0rlNXs",
    tags: ["intermediario", "treinoD"],
  ),
  Exercicio(
    nome: "Elevação Frontal Halter",
    imagem: "assets/images/elevacao-frontal.png",
    tipoEquipamento: "academia",
    linkYoutube: "NxSuojHZa8k",
    tags: ["intermediario", "treinoD"],
  ),
  Exercicio(
    nome: "Encolhimento Barra",
    imagem: "assets/images/encolhimento.png",
    tipoEquipamento: "academia",
    linkYoutube: "RhGjwIUe16E",
    tags: ["intermediario", "treinoD"],
  ),
  Exercicio(
    nome: "Arnold Press",
    imagem: "assets/images/arnald-press.png",
    tipoEquipamento: "academia",
    linkYoutube: "jeJttN2EWCo",
    tags: ["intermediario", "treinoD"],
  ),

  // ----- ACADEMIA - AVANÇADO -----
  Exercicio(
    nome: "Supino Reto Barra",
    imagem: "assets/images/supino-reto-barra.png",
    tipoEquipamento: "academia",
    linkYoutube: "pCPyqW60Wuk",
    tags: ["avancado", "treinoA"],
  ),
  Exercicio(
    nome: "Supino Inclinado Halter",
    imagem: "assets/images/supino_inclinado.png",
    tipoEquipamento: "academia",
    linkYoutube: "F4Q1g2z8MWM",
    tags: ["avancado", "treinoA"],
  ),
  Exercicio(
    nome: "Crucifixo Inclinado Halter",
    imagem: "assets/images/crucifixo-inclinado-halteres.png",
    tipoEquipamento: "academia",
    linkYoutube: "uy9Xk3SVrms",
    tags: ["avancado", "treinoA"],
  ),
  Exercicio(
    nome: "Crossover Polia Alta",
    imagem: "assets/images/crossover-polia-alta.png",
    tipoEquipamento: "academia",
    linkYoutube: "jqTlJt3JXzQ",
    tags: ["avancado", "treinoA"],
  ),
  Exercicio(
    nome: "Flexão de Braço",
    imagem: "assets/images/flexao.png",
    tipoEquipamento: "peso_corporal",
    linkYoutube: "dHgoYiCraCw",
    tags: ["avancado", "treinoA"],
  ),

  Exercicio(
    nome: "Barra Fixa",
    imagem: "assets/images/barra-fixa.png",
    tipoEquipamento: "academia",
    linkYoutube: "thg6cGXSlvY",
    tags: ["avancado", "treinoB"],
  ),
  Exercicio(
    nome: "Remada Curvada Barra",
    imagem: "assets/images/remada-curvada-barra.png",
    tipoEquipamento: "academia",
    linkYoutube: "TfxJMertfsw",
    tags: ["avancado", "treinoB"],
  ),
  Exercicio(
    nome: "Remada Unilateral Halter",
    imagem: "assets/images/remada-unilateral-halter.png",
    tipoEquipamento: "academia",
    linkYoutube: "m4h4jT9patY",
    tags: ["avancado", "treinoB"],
  ),
  Exercicio(
    nome: "Pulldown Polia Alta",
    imagem: "assets/images/pulldown-polia-alta.png",
    tipoEquipamento: "academia",
    linkYoutube: "v6-QIOY0nW0",
    tags: ["avancado", "treinoB"],
  ),
  Exercicio(
    nome: "Face Pull",
    imagem: "assets/images/facepull.png",
    tipoEquipamento: "academia",
    linkYoutube: "0Po47vvj9g4",
    tags: ["avancado", "treinoB"],
  ),

  Exercicio(
    nome: "Desenvolvimento Militar Barra",
    imagem: "assets/images/desenvolvimento-com-halteres.png",
    tipoEquipamento: "academia",
    linkYoutube: "L-iQfHVeuVg",
    tags: ["avancado", "treinoC"],
  ),
  Exercicio(
    nome: "Elevação Lateral Halter",
    imagem: "assets/images/elevacao-lateral.png",
    tipoEquipamento: "academia",
    linkYoutube: "IwWvZ0rlNXs",
    tags: ["avancado", "treinoC"],
  ),
  Exercicio(
    nome: "Elevação Frontal Halter",
    imagem: "assets/images/elevacao-frontal.png",
    tipoEquipamento: "academia",
    linkYoutube: "NxSuojHZa8k",
    tags: ["avancado", "treinoC"],
  ),
  Exercicio(
    nome: "Encolhimento Barra",
    imagem: "assets/images/encolhimento.png",
    tipoEquipamento: "academia",
    linkYoutube: "RhGjwIUe16E",
    tags: ["avancado", "treinoC"],
  ),
  Exercicio(
    nome: "Arnold Press",
    imagem: "assets/images/arnald-press.png",
    tipoEquipamento: "academia",
    linkYoutube: "jeJttN2EWCo",
    tags: ["avancado", "treinoC"],
  ),

  Exercicio(
    nome: "Agachamento Livre",
    imagem: "assets/images/agachamento-livre.png",
    tipoEquipamento: "academia",
    linkYoutube: "IGf9fR4Y7Iw",
    tags: ["avancado", "treinoD"],
  ),
  Exercicio(
    nome: "Leg Press",
    imagem: "assets/images/legpress.png",
    tipoEquipamento: "academia",
    linkYoutube: "nY8UsiAqwds",
    tags: ["avancado", "treinoD"],
  ),
  Exercicio(
    nome: "Cadeira Extensora",
    imagem: "assets/images/cadeira-extensora.png",
    tipoEquipamento: "academia",
    linkYoutube: "el3oHblB5DM",
    tags: ["avancado", "treinoD"],
  ),
  Exercicio(
    nome: "Cadeira Flexora",
    imagem: "assets/images/cadeira-flexora.png",
    tipoEquipamento: "academia",
    linkYoutube: "Zss6E3VU6X0",
    tags: ["avancado", "treinoD"],
  ),
  Exercicio(
    nome: "Panturrilha em Pé",
    imagem: "assets/images/panturrilha.png",
    tipoEquipamento: "academia",
    linkYoutube: "95MEoNZKaP0",
    tags: ["avancado", "treinoD"],
  ),

  Exercicio(
    nome: "Rosca Direta Barra",
    imagem: "assets/images/rosca_direta.png",
    tipoEquipamento: "academia",
    linkYoutube: "s4B8UW3BMqk",
    tags: ["avancado", "treinoE"],
  ),
  Exercicio(
    nome: "Rosca Alternada Halter",
    imagem: "assets/images/rosca_alternada.png",
    tipoEquipamento: "academia",
    linkYoutube: "S1HAcTVQVYE",
    tags: ["avancado", "treinoE"],
  ),
  Exercicio(
    nome: "Tríceps Testa Barra",
    imagem: "assets/images/triceps_testa.png",
    tipoEquipamento: "academia",
    linkYoutube: "VakpIeaaeXA",
    tags: ["avancado", "treinoE"],
  ),
  Exercicio(
    nome: "Tríceps Corda Polia",
    imagem: "assets/images/triceps_corda.png",
    tipoEquipamento: "academia",
    linkYoutube: "dTqDKC0D6P4",
    tags: ["avancado", "treinoE"],
  ),
  Exercicio(
    nome: "Rosca Martelo",
    imagem: "assets/images/rosca_martelo.png",
    tipoEquipamento: "academia",
    linkYoutube: "0qkQy8V2FC0",
    tags: ["avancado", "treinoE"],
  ),
];
